### PR TITLE
[WIP] General code cleanup before public release

### PR DESCRIPTION
**Pull request by johnmyleswhite**
Still working on this, @simonster, but here's the mild merge conflict I would have had with #11

### CODE REVIEW

**Comment by KristofferC** [comment]
Really like the thorough documentation.

**Comment by johnmyleswhite** [comment]
Thanks, @KristofferC!

**Comment by KristofferC** [comment]
Anything that me/someone can do to help this get merged?

**Comment by johnmyleswhite** [comment]
Merging this was a good call. Thanks for the ping, @KristofferC. I tend to want to finish the whole redesign in a single pass, which was why this PR was languishing.

Still need to handle a few more issues before this package is ready for public release.

**Comment by KristofferC** [comment]
Just give a call if I can help with something. I like to benchmark stuff (hehe) so this package is really valuable to me.

**Pull request merged**
